### ISSUE TITLE
Предлагаю добавить к "def snowflake()" новый параметр.

### ISSUE THREAD

**Issue by ziggurat-of-knowledge** [suguby/simple_draw#1]
Новый параметр для "def snowflake()", который будет отвечать за кол-во лучей у снежинки.
Просто 
Место ответвления лучиков - есть, 
Дина лучиков - есть,
Угол отклонения лучиков - есть,
а кол-во лучиков - нету.

http://joxi.ru/brRW1xRfJDReEm

**Comment by suguby** [comment]
это лишнее
