### ISSUE TITLE
Возможно ли сделать следующие....

### ISSUE THREAD

**Issue by ziggurat-of-knowledge** [suguby/simple_draw#3]
Например есть круг:

```
import simple_draw as sd

point = sd.random_point()
sd.circle(center_position=point, radius=sd.randint(15, 50), width=0)
```

можно ли сделать так чтобы например мы к переменной circle присваиваем круг и можем через эту переменную обращаться к его параметрам...

```
point = sd.random_point()
circle = sd.circle(center_position=point, radius=sd.randint(15, 50), width=0)
print(circle.center_position)
print(circle.radius)
```
...?

**Comment by suguby** [comment]
для такой простой библиотеки - нет.  можешь сам создать класс окружностей и там брать аттрибуты.
